services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net

  celery:
    build:
     context: ./api
    command: celery -A celery_app worker --loglevel=info
    environment:
      REDIS_URL: redis:6379
    volumes:
      - ./api:/app
    depends_on:
      - redis
    restart: always
    networks:
      - net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - net

  logic:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: logic
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: chat
      DB_USER: postgres
      DB_PASS: postgres
      AUTH_SECRET: 5SpxMnjOUeT4zTLKmikTSoovwMY6NbfDyNY6CNUGLsU
      VER_SECRET: ESxXRfHQGfZcWiau83TrGtk0R43NaQUOSMJX6qKtT0E
      API_TOKEN: 7919252479:AAHrzN_I7o_yxoUa03I5sr2_nM6HrW6vMOg
      REDIS_URL: redis:6379
    depends_on:
      - postgres
      - redis
      - celery
    ports:
      - "8000:8000"
    networks:
      - net

  view:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: view
    ports:
      - "3000:3000"
    depends_on:
      - logic
    networks:
      - net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - view
      - logic
    networks:
      - net

volumes:
  postgres_data:

networks:
  net: