services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net

  logic:
    build:
      context: ./chatLogic
      dockerfile: Dockerfile
    container_name: logic
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    networks:
      - net

  view:
    build:
      context: ./chatView
      dockerfile: Dockerfile
    container_name: view
    ports:
      - "3000:3000"
    networks:
      - net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - view
      - logic
    networks:
      - net


volumes:
  postgres_data:

networks:
  net:
